name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # Ou a branch que você deseja que acione a implantação

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./ # O diretório do seu repositório que será enviado
        server-dir: ${{ secrets.FTP_TARGET_DIR }} # O diretório de destino no servidor
        protocol: ftp # Protocolo a ser utilizado
